spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fitpower_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

  output:
    ansi:
      enabled: always # permite ver el log como colores
server:
  port: 8080
logging:
  level:
    root: info # permite ver los logs de consola

